### ISSUE TITLE
Setup client (TS, React, Chakra UI)

### ISSUE THREAD

**Issue by hbakardzhiev** [HermesPlatform/hermes-client#1]

**Comment by VikVelev** [comment]
Changed from MUI to Chakra as it seems way better.

**Comment by VikVelev** [comment]
Not setting up SASS as Chakra has it's own css-like engine for everything we need.

**Comment by VikVelev** [comment]
Forgot to create new branch and do PR.
Maybe we should prohibit merging on 'main'. I'll set that up.
